### ISSUE TITLE
launcher.sh generated  AttributeError: 'super' object has no attribute 'on_disabled'

### ISSUE THREAD

**Issue by chaoman** [Joelzeller/CoPilot#11]
I was able to figure out the dependencies and defect discussed in #6. However, I have got a new error when launching through launcher.sh. I have made launcher.sh executable but got the following error. Any hint or help is appreciated. 

```pi@raspberrypi:~/CoPilot $ ./launcher.sh
[INFO   ] [Logger      ] Record log in /root/.kivy/logs/kivy_18-05-29_3.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-6c7fce6, 20180528
[INFO   ] [Python      ] v2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO   ] [GL          ] OpenGL vendor <Broadcom>
[INFO   ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Loader      ] using a thread pool of 2 workers
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
 Traceback (most recent call last):
   File "main.py", line 2077, in <module>
     MainApp().run()
   File "/usr/local/lib/python2.7/dist-packages/kivy/app.py", line 799, in run
     self.load_kv(filename=self.kv_file)
   File "/usr/local/lib/python2.7/dist-packages/kivy/app.py", line 596, in load_kv
     root = Builder.load_file(rfilename)
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/builder.py", line 301, in load_file
     return self.load_string(data, **kwargs)
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/builder.py", line 400, in load_string
     self._apply_rule(widget, parser.root, parser.root)
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/builder.py", line 630, in _apply_rule
     e), cause=tb)
 kivy.lang.builder.BuilderException: Parser: File "/home/pi/CoPilot/main.kv", line 1297:
 ...
    1295:                                                                               on_press: Animation(y=-100, duration=0).start(dock_normal_power)
    1296:                                                                               font_size: 30
 >> 1297:                                                                               disabled: True
    1298:                                                               JZLargeButton:
    1299:                                                                               text: "Night Gauge"
 ...
 AttributeError: 'super' object has no attribute 'on_disabled'
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/builder.py", line 619, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 33, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 483, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 1470, in kivy.properties.AliasProperty.set
   File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 1318, in set_disabled
     self.inc_disabled()
   File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 1325, in inc_disabled
     self.property('disabled').dispatch(self)
   File "kivy/properties.pyx", line 562, in kivy.properties.Property.dispatch
   File "kivy/properties.pyx", line 579, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "/home/pi/CoPilot/kivymd/button.py", line 495, in on_disabled
     super(JZLargeButton, self).on_disabled(instance, value)
```

Thanks,

**Comment by ngrontas** [comment]
@chaoman did you ever find a fix to this?

**Comment by chaoman** [comment]
@ngrontas No....I stopped.

**Comment by chaoman** [comment]
Finally got this fixed. It turned out that you don't have to comment out the img_pygame.py file per the instruction. However, you have to enlarge the GPU memory split to 256 MB in order to get PNGs for gauge to show correctly.

**Comment by Raiphy-Jerez** [comment]
@chaoman how exactly did you solve this problem. Im looking into making an image of this for beginners to use. This seems like a project that would benefit from some attention.

**Comment by doomsdail** [comment]
Hello. I'm trying to start this project on my raspberry 3. It also gives me the same error, I increased the memory of the GPU to 256mb but I can't solve. Can you give me some suggestions?
