### ISSUE TITLE
start problem

### ISSUE THREAD

**Issue by fabian93** [Joelzeller/CoPilot#3]
sudo python main.py
[INFO   ] [Logger      ] Record log in /root/.kivy/logs/kivy_18-02-11_3.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-a4d93d6, 20180210
[INFO   ] [Python      ] v2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170124]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO   ] [GL          ] OpenGL vendor <Broadcom>
[INFO   ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "main.py", line 2077, in <module>
     MainApp().run()
   File "/usr/local/lib/python2.7/dist-packages/kivy/app.py", line 799, in run
     self.load_kv(filename=self.kv_file)
   File "/usr/local/lib/python2.7/dist-packages/kivy/app.py", line 596, in load_kv
     root = Builder.load_file(rfilename)
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/builder.py", line 301, in load_file
     return self.load_string(data, **kwargs)
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/builder.py", line 350, in load_string
     parser = Parser(content=string, filename=fn)
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/parser.py", line 392, in __init__
     self.parse(content)
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/parser.py", line 498, in parse
     self.execute_directives()
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/parser.py", line 462, in execute_directives
     mod = __import__(package)
   File "/home/pi/CoPilot/kivymd/tabs.py", line 98, in <module>
     class MDTabHeader(MDFlatButton):
   File "/home/pi/CoPilot/kivymd/tabs.py", line 101, in MDTabHeader
     width = BoundedNumericProperty(dp(None), min=dp(72), max=dp(264), errorhandler=lambda x: dp(72))
   File "/usr/local/lib/python2.7/dist-packages/kivy/metrics.py", line 136, in dp
     return dpi2px(value, 'dp')
   File "kivy/properties.pyx", line 291, in kivy.properties.dpi2px
   File "kivy/properties.pyx", line 299, in kivy.properties.dpi2px
 TypeError: float() argument must be a string or a number

**Comment by Joelzeller** [comment]
Hi Fabian,

Sorry for the late reply. I am in my final semester at college and things are quite busy right now.

Fortunately, someone else had this same error and emailed me how he fixed it. Please see below and make the following change:


To fix this error I've modified the "/home/pi/CoPilot/kivymd/tabs.py" line 101 from:

width = BoundedNumericProperty(dp(None), min=dp(72), max=dp(264), errorhandler=lambda x: dp(72))

to:

width = BoundedNumericProperty(dp(0), min=dp(72), max=dp(264), errorhandler=lambda x: dp(72))

I hope this fix works for you as well! Please let me know if it does or if you get any other errors, I will do my best to help!

Joel Z

**Comment by fabian93** [comment]
It works. Thank you very much and I wish you good luck at college. I would like to a solution to the bluetooth problem, "It works best if you start audio on the screen"
