### ISSUE TITLE
Cannot get CoPilot to run

### ISSUE THREAD

**Issue by asmith2073** [Joelzeller/CoPilot#6]
I have no clue what I am doing wrong lol. I double checked all packages were installed and I am running python 2.7. I attached a picture to hopefully help. Thank you in advanced!
![capture](https://user-images.githubusercontent.com/37128718/37069558-8a4418bc-2179-11e8-9b81-64191ec3dfd9.PNG)

**Comment by rcpilotp51** [comment]
I have the same issue thanks

**Comment by MarioBG** [comment]
I had the same issue and was able to fix it by changing the tabs.py file and changing the line displayed from dp(None) [...] to dp(0) [...]; however, do expect a myriad of more issues after that. With some luck we'll be able to fix them collaboratively

**Comment by rcpilotp51** [comment]
@MarioBG have you fixed any of the other issues:
https://github.com/Joelzeller/CoPilot/issues/7 

or anything with concurrent.futures

Thanks

**Comment by asmith2073** [comment]
Thanks @MarioBG ! That worked!

**Comment by rcpilotp51** [comment]
hey all - here is another one for the lot:

`
[INFO   ] [Kivy        ] v1.10.1.dev0, git-1ccd294, 20180308
[INFO   ] [Python      ] v2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif                             (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO   ] [GL          ] OpenGL vendor <Broadcom>
[INFO   ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Loader      ] using a thread pool of 2 workers
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
 Traceback (most recent call last):
   File "main.py", line 2077, in <module>
     MainApp().run()
   File "/usr/local/lib/python2.7/dist-packages/kivy/app.py", line 799, in run
     self.load_kv(filename=self.kv_file)
   File "/usr/local/lib/python2.7/dist-packages/kivy/app.py", line 596, in load_                            kv
     root = Builder.load_file(rfilename)
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/builder.py", line 301,                             in load_file
     return self.load_string(data, **kwargs)
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/builder.py", line 382,                             in load_string
     self._apply_rule(widget, parser.root, parser.root)
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/builder.py", line 612,                             in _apply_rule
     e), cause=tb)
 kivy.lang.builder.BuilderException: Parser: File "/home/pi/CoPilot/main.kv", li                            ne 1297:
 ...
    1295:                                                                      o                            n_press: Animation(y=-100, duration=0).start(dock_normal_power)
    1296:                                                                      f                            ont_size: 30
 >> 1297:                                                                      d                            isabled: True
    1298:                                                               JZLargeB                            utton:
    1299:                                                                      t                            ext: "Night Gauge"
 ...
 AttributeError: 'super' object has no attribute 'on_disabled'
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/builder.py", line 601,                             in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 33, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 478, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 1471, in kivy.properties.AliasProperty.set
   File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 1313,                             in set_disabled
     self.inc_disabled()
   File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 1320,                             in inc_disabled
     self.property('disabled').dispatch(self)
   File "kivy/properties.pyx", line 554, in kivy.properties.Property.dispatch
   File "kivy/properties.pyx", line 571, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "/home/pi/CoPilot/kivymd/button.py", line 495, in on_disabled
     super(JZLargeButton, self).on_disabled(instance, value)
`

**Comment by MarioBG** [comment]
Yeah, @rcpilotp51 that's a funny one - just go to main.kv, look for every "disabled = true" (on the Worms and Night clocks) and delete them. I think that's one of the last ones to get it running. I need to test it with the touchscreen, however, since it doesn't appear to recognise clicks where it should (and it doesn't display the mouse cursor either, so fat chance). I'll get back to it eventually.

**Comment by rcpilotp51** [comment]
good call. I'll try that this evening. looks promising - i ssh'd into my pi
and deleted the super call i didnt get any errors other than the png
interface one - hopefully that will work on the display...(fingers
crossed)  @MarioBG try using a stylus to drag a square on the desktop to
see if you need to do the calibration script. Thank again

**Comment by rcpilotp51** [comment]
@MarioBG I get nothing but a white screen and 
"libpng warning: Interlace handling should be turned on when using png_read_image"

**Comment by rcpilotp51** [comment]
Is there anywhere i can activate Interlace??

**Comment by rcpilotp51** [comment]
I got everything working and am even programming some new features. radio over rtl-sdr and gps updating the map. I also have some volume controls working and playing audio through the pi rather than just controlling the aux... should be pretty cool.

**Comment by chaoman** [comment]
@rcpilotp51 - I followed @MarioBG's fix for  tabs.py file and changing the line displayed from dp(None) [...] to dp(0) [...]; and it's referenced on https://gitlab.com/kivymd/KivyMD/commit/e81c02afbca915a4d71c85d3486f6710b53df2c1.

After fixing the dp issue, now I ran into this problem.

```pi@raspberrypi:~/CoPilot $ python main.py
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_18-05-28_4.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-6c7fce6, 20180528
[INFO   ] [Python      ] v2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif                                                                  (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO   ] [GL          ] OpenGL vendor <Broadcom>
[INFO   ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "main.py", line 2077, in <module>
     MainApp().run()
   File "/usr/local/lib/python2.7/dist-packages/kivy/app.py", line 799, in run
     self.load_kv(filename=self.kv_file)
   File "/usr/local/lib/python2.7/dist-packages/kivy/app.py", line 596, in load_                                                                 kv
     root = Builder.load_file(rfilename)
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/builder.py", line 301,                                                                  in load_file
     return self.load_string(data, **kwargs)
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/builder.py", line 400,                                                                  in load_string
     self._apply_rule(widget, parser.root, parser.root)
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/builder.py", line 585,                                                                  in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/builder.py", line 585,                                                                  in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/builder.py", line 585,                                                                  in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/builder.py", line 582,                                                                  in _apply_rule
     child = cls(__no_builder=True)
   File "/home/pi/CoPilot/mapview/view.py", line 496, in __init__
     self.add_widget(self._scatter)
   File "/home/pi/CoPilot/mapview/view.py", line 543, in add_widget
     super(MapView, self).add_widget(widget)
   File "/usr/local/lib/python2.7/dist-packages/kivy/uix/widget.py", line 534, i                                                                 n add_widget
     widget._disabled_count = self._disabled_count
 AttributeError: 'MapView' object has no attribute '_disabled_count'
pi@raspberrypi:~/CoPilot $
```
Have you experienced this issue? How did you get it running?

**Comment by chaoman** [comment]
> I got everything working and am even programming some new features. radio over rtl-sdr and gps updating the map. I also have some volume controls working and playing audio through the pi rather than just controlling the aux... should be pretty cool.

@rcpilotp51 - how did you address the white Interlace issue? I got into the same issue as you had earlier.

**Comment by rcpilotp51** [comment]
Make sure you install the correct version of kivy and follow the
instructions to remove the exceptions. I'm also running a non gui version
of Raspian (cli only)

**Comment by chaoman** [comment]
I did try to remove the exception like below from file `sudo nano /usr/local/lib/python2.7/dist-packages/kivy/core/image/img_pygame.py`
```
        # image loader work only with rgb/rgba image
        if fmt not in ('rgb', 'rgba'):
            try:
                imc = im.convert(32)
                fmt = 'rgba'
            except:
                try:
                    imc = im.convert_alpha()
                    fmt = 'rgba'
                except:
                    #Logger.warning(
                    #   'Image: Unable to convert image %r to rgba (was %r)' %
                    #   (filename, im.fmt))
                    #raise
            im = imc
```

Still no luck. I am running Raspbian stretch but it shouldn't be much different than the Raspbian cli only version. I still got the white screen. Any other hint?

**Comment by chaoman** [comment]
Finally got it to run without commenting img_pygame.py file. The white screen is caused by insufficient GPU memory to render gauge related PNGs. I bumped the GPU split memory to 256 MB and got everything working.
