### ISSUE TITLE
mapview concurrent.futures

### ISSUE THREAD

**Issue by rcpilotp51** [Joelzeller/CoPilot#8]
Ive installed futures - do you know why I am getting this error?

Traceback (most recent call last):
   File "main.py", line 47, in <module>
     from kivy.garden.mapview import MapView
   File "/usr/local/lib/python2.7/dist-packages/kivy/garden/__init__.py", line 100, in load_module
     return self._load_module(fullname, moddir)
   File "/usr/local/lib/python2.7/dist-packages/kivy/garden/__init__.py", line 104, in _load_module
     ('', '', imp.PKG_DIRECTORY))
   File "/home/pi/CoPilot/libs/garden/garden.mapview/__init__.py", line 3, in <module>
     from .mapview import *
   File "/home/pi/CoPilot/libs/garden/garden.mapview/mapview/__init__.py", line 30, in <module>
     from mapview.source import MapSource
   File "/home/pi/CoPilot/libs/garden/garden.mapview/mapview/source.py", line 9, in <module>
     from mapview.downloader import Downloader
   File "/home/pi/CoPilot/libs/garden/garden.mapview/mapview/downloader.py", line 8, in <module>
     from concurrent.futures import ThreadPoolExecutor, TimeoutError, as_completed
 ImportError: No module named concurrent.futures

THanks for your help

**Comment by rcpilotp51** [comment]
i removed sudo from the launcher.sh and dont get this error any longer

**Comment by chaoman** [comment]
You can also resolve this by installing futures from the mapview path.

```pi@raspberrypi:~/CoPilot/libs/garden/garden.mapview/mapview $ sudo pip install futures```
